#include <stdint.h>
#include "tm4c123gh6pm.h"
#include "ST7735.h"
#include "Random.h"
#include "TExaS.h"
#include "ADC.h"
#include "MainMenu.h"
#include "Timer1.h"
#include "Port_Init.h"
#include "Sound.h"
int8_t DistanceXDown1(void);
int8_t DistanceXDown2(void);
int8_t DistanceYLeft1(void);
int8_t DistanceYLeft2(void);
int8_t DistanceXUp1(void);
int8_t DistanceXUp2(void);
int8_t DistanceYRight1(void);
int8_t DistanceYRight2(void);
int BestDistance(void);
void Uppp(void);
void Downnn(void);
void Lefttt(void);
void Righttt(void);
void Upppp(void);
void Downnnn(void);
void Leftttt(void);
void Rightttt(void);
void Versusss(void);
void Versussss(void);
void GPIOPortB_Handler(void);
void DrawWalls2(void);
void CPU(void);
